name: Build HIPPP

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ ninja-build wget
          wget -qO - http://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
          echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/6.0/ focal main' | sudo tee /etc/apt/sources.list.d/rocm.list
          sudo apt-get update
          sudo apt-get install -y hip-base hipcc hip-dev hip-runtime-amd rocm-device-libs
          echo "/opt/rocm/bin" >> $GITHUB_PATH
          echo "export PATH=/opt/rocm/bin:$PATH" >> $GITHUB_ENV
          echo "export HIP_PATH=/opt/rocm" >> $GITHUB_ENV
          echo "export ROCM_PATH=/opt/rocm" >> $GITHUB_ENV

      - name: Fake rocm_agent_enumerator for CI
        run: |
          if [ ! -f /opt/rocm/bin/rocm_agent_enumerator ]; then
            echo -e '#!/bin/bash\necho gfx900' | sudo tee /opt/rocm/bin/rocm_agent_enumerator > /dev/null
            sudo chmod +x /opt/rocm/bin/rocm_agent_enumerator
          fi

      - name: Configure CMake
        run: cmake -B build -G Ninja -DHIP_ROOT_DIR=/opt/rocm -DHIP_ARCHITECTURES=gfx900 -DHIP_DEVICE_LIB_PATH=/opt/rocm/amdgcn/bitcode

      - name: Build
        run: cmake --build build

      # - name: Test
      #   run: ctest --test-dir build