name: Build HIPPP

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: rocm/dev-ubuntu-22.04:6.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: apt-get update && apt-get install -y cmake g++ ninja-build

      - name: Fake rocm_agent_enumerator for CI
        run: |
          if [ ! -f /opt/rocm/bin/rocm_agent_enumerator ]; then
            echo -e '#!/bin/bash\necho gfx900' > /opt/rocm/bin/rocm_agent_enumerator
            chmod +x /opt/rocm/bin/rocm_agent_enumerator
          fi

      - name: Configure CMake
        run: cmake -B build -G Ninja -DHIP_ROOT_DIR=/opt/rocm -DHIP_ARCHITECTURES=gfx900

      - name: Build
        run: cmake --build build